name: Deploy on stage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Extra
        run: |
          rm -rf ./src/app/mocked_api/

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      # - name: Test
      #   run: pnpm run test

      - name: Build
        env:
          NEXT_PUBLIC_ENV: "stage"
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL_STAGE }}
        run: pnpm run build

      - name: Static
        run: |
          mv ./.next/static/ ./.next/standalone/.next
          mv ./public/ ./.next/standalone

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_STAGE }}

      - name: Copy files via SCP
        run: |
          scp -r -o StrictHostKeyChecking=no ./.next/standalone/.next ${{ secrets.SERVER_USER_STAGE }}@${{ secrets.SERVER_IP_STAGE }}:${{ secrets.DEPLOY_PATH_STAGE }}/
          scp -r -o StrictHostKeyChecking=no ./.next/standalone/public ${{ secrets.SERVER_USER_STAGE }}@${{ secrets.SERVER_IP_STAGE }}:${{ secrets.DEPLOY_PATH_STAGE }}/
          scp -r -o StrictHostKeyChecking=no ./.next/standalone/server.js ${{ secrets.SERVER_USER_STAGE }}@${{ secrets.SERVER_IP_STAGE }}:${{ secrets.DEPLOY_PATH_STAGE }}
          scp -r -o StrictHostKeyChecking=no ./.next/standalone/package.json ${{ secrets.SERVER_USER_STAGE }}@${{ secrets.SERVER_IP_STAGE }}:${{ secrets.DEPLOY_PATH_STAGE }}
          scp -r -o StrictHostKeyChecking=no ./docker-compose.yaml ${{ secrets.SERVER_USER_STAGE }}@${{ secrets.SERVER_IP_STAGE }}:${{ secrets.DEPLOY_PATH_STAGE }}
          scp -r -o StrictHostKeyChecking=no ./Dockerfile ${{ secrets.SERVER_USER_STAGE }}@${{ secrets.SERVER_IP_STAGE }}:${{ secrets.DEPLOY_PATH_STAGE }}
          scp -r -o StrictHostKeyChecking=no ./.dockerignore ${{ secrets.SERVER_USER_STAGE }}@${{ secrets.SERVER_IP_STAGE }}:${{ secrets.DEPLOY_PATH_STAGE }}

      - name: Run Docker Compose
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_STAGE_STAGE }}@${{ secrets.SERVER_IP_STAGE_STAGE }} "cd ${{ secrets.DEPLOY_PATH_STAGE }} && docker compose up -d --build"
